# Generated by Django 5.0.3 on 2024-04-07 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapasapp', '0002_account_delete_dish'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
    ]
